

server:
  port: 8090

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: studentModule
        uri: lb://student-service
        predicates:
        - Path=/student/**
      - id: courseModule
        uri: lb://course-service
        predicates:
        - Path=/course/**
      - id: ucmModule
        uri: lb://ucm-service
        predicates:
        - Path=/nimaiUCM/**
      - id: adminModule
        uri: lb://admin-service
        predicates:
        - Path=/nimaiAdminApiUat/**
      - id: emailModule
        uri: lb://email-service
        predicates:
        - Path=/nimaiEmail/**
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka